### ISSUE TITLE
Screen.capture memory leak Windows

### ISSUE THREAD

**Issue by Strugur** [octalmage/robotjs#499]
let robot = require("robotjs");
setInterval(function(){
    robot.screen.capture(0,0,300,300);
}, 20);
Doesnt matter what interval time i will put.
The amount of memory taken up by node steadily increases and don't stop.

**Comment by Razi91** [comment]
It's not memory leak itself, but garbage collector has no time to collect unused buffers. It's Node's architecture problem.

I've made a fix for that on my branch (https://github.com/Razi91/robotjs/tree/captureScreen-reuse-buffer). You just reuse previous buffer, so it doesn't create new one with every frame. It's much more efficient.

**Comment by Strugur** [comment]
Thank you !!!!👍

пн, 12 авг. 2019 г. в 23:11, jkonieczny <notifications@github.com>:

**Comment by Strugur** [comment]
> It's not memory leak itself, but garbage collector has no time to collect unused buffers. It's Node's architecture problem.
> 
> I've made a fix for that on my branch (https://github.com/Razi91/robotjs/tree/captureScreen-reuse-buffer). You just reuse previous buffer, so it doesn't create new one with every frame. It's much more efficient.

new profblem 
let buf = Buffer.alloc(477*327*4);
let s1 = robot.screen.capture(0,0,477,327,buf);

Error:
C:\learn\Node\far__away_FRONT\node_modules\robotjs\index.js:38
            b = robotjs.captureScreenRe(x, y, width, height, buffer);
                        ^

TypeError: robotjs.captureScreenRe is not a function
    at Object.module.exports.screen.capture (C:\learn\Node\far__away_FRONT\node_modules\robotjs\index.js:38:25)
    at Object.<anonymous> (C:\learn\Node\far__away_FRONT\serv1.js:4:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by Razi91** [comment]
Looks like you don't have module rebuilded. I'm sorry, but I don't know how to do it for Windows, on Linux it builds it when insalling through npm/yarn. Maybe I'll try to do it, but I don't promise anything.

**Comment by oktapodia** [comment]
It looks like this issue has been solved.
You may reopen this issue if it has been closed in error.

**Comment by Mystraht** [comment]
The error is still present as today, can't run "robot.screen.capture" in a loop without having application crashing after some time

**Comment by Lucidare** [comment]
From what I can tell, this issue still exists since my memory usage keeps going up as long

**Comment by Mystraht** [comment]
> It's not memory leak itself, but garbage collector has no time to collect unused buffers. It's Node's architecture problem.
> 
> I've made a fix for that on my branch (https://github.com/Razi91/robotjs/tree/captureScreen-reuse-buffer). You just reuse previous buffer, so it doesn't create new one with every frame. It's much more efficient.

I use this solution, it works perfectly thanks to @Razi91 but it would be awesome to see this feature fixed in the main repo.

**Comment by atdykema** [comment]
> > It's not memory leak itself, but garbage collector has no time to collect unused buffers. It's Node's architecture problem.
> > I've made a fix for that on my branch (https://github.com/Razi91/robotjs/tree/captureScreen-reuse-buffer). You just reuse previous buffer, so it doesn't create new one with every frame. It's much more efficient.
> 
> I use this solution, it works perfectly thanks to @Razi91 but it would be awesome to see this bug fixed in the main repo.

How are you able to implement the new repository? I tried copy & pasting the edited bits into my robotjs but it didnt end up working. Any advice with this?

**Comment by atdykema** [comment]
> Looks like you don't have module rebuilded. I'm sorry, but I don't know how to do it for Windows, on Linux it builds it when insalling through npm/yarn. Maybe I'll try to do it, but I don't promise anything.

I'm having trouble implementing your build, any advice? I've tried patching my current robotjs but that hasnt seemed to work
